use std::sync::Arc;

use forex_db::DatabaseConnection;
use forex_ingestor::YahooClient;
use rspc_legacy::Router as LegacyRouter;

pub mod ctx;
pub mod routes;

pub use ctx::{AppConfig, Ctx};

pub fn build_legacy_router() -> LegacyRouter<Ctx> {
    let r = LegacyRouter::<Ctx>::new();
    let r = routes::meta::mount(r);
    let r = routes::notes::mount(r);
    let r = routes::predictions::mount(r);
    let r = routes::backtests::mount(r);
    let r = routes::practice::mount(r);
    let r = routes::trades::mount(r);
    let r = routes::candles::mount(r);
    let r = routes::ingestion::mount(r);
    r.build()
}

pub fn build_modern_router() -> rspc::Router<Ctx> {
    build_legacy_router().into()
}

pub fn build_procedures() -> Result<(rspc::Procedures<Ctx>, rspc::Types), String> {
    build_modern_router()
        .build()
        .map_err(|errs| format!("{errs:?}"))
}

pub fn export_typescript_bindings(types: &rspc::Types, output_path: &std::path::Path) -> anyhow::Result<()> {
    rspc::Typescript::default()
        .header("// Auto-generated by forex-api/export-bindings. DO NOT EDIT.\n")
        .export_to(output_path, types)
        .map_err(|e| anyhow::anyhow!("export bindings: {e}"))?;
    Ok(())
}

pub fn make_ctx(db: Arc<DatabaseConnection>) -> Ctx {
    let yahoo = Arc::new(YahooClient::new().expect("yahoo client"));
    Ctx { db, yahoo, config: AppConfig::default() }
}

pub fn make_ctx_with_config(db: Arc<DatabaseConnection>, config: AppConfig) -> Ctx {
    let yahoo = Arc::new(YahooClient::new().expect("yahoo client"));
    Ctx { db, yahoo, config }
}
