[package]
name = "forex-ingestor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
forex-core = { workspace = true }
forex-db = { workspace = true }
uuid = { workspace = true }
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "gzip"] }
tokio = { workspace = true }
tokio-util = "0.7"
futures = "0.3"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
sea-orm = { version = "1", default-features = false, features = ["macros", "runtime-tokio-rustls"] }
