/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as IngestionRouteImport } from './routes/ingestion'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PlaybookRouteImport } from './routes/playbook'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as PairPairIdRouteImport } from './routes/pair.$pairId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const IngestionRoute = IngestionRouteImport.update({
  id: '/ingestion',
  path: '/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaybookRoute = PlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const PairPairIdRoute = PairPairIdRouteImport.update({
  id: '/pair/$pairId',
  path: '/pair/$pairId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/forecast': typeof ForecastRoute
  '/ingestion': typeof IngestionRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/practice': typeof PracticeRoute
  '/predictions': typeof PredictionsRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/forecast': typeof ForecastRoute
  '/ingestion': typeof IngestionRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/practice': typeof PracticeRoute
  '/predictions': typeof PredictionsRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/backtest': typeof BacktestRoute
  '/forecast': typeof ForecastRoute
  '/ingestion': typeof IngestionRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/playbook': typeof PlaybookRoute
  '/practice': typeof PracticeRoute
  '/predictions': typeof PredictionsRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/forecast'
    | '/ingestion'
    | '/learning'
    | '/notes'
    | '/playbook'
    | '/practice'
    | '/predictions'
    | '/review'
    | '/pair/$pairId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/backtest'
    | '/forecast'
    | '/ingestion'
    | '/learning'
    | '/notes'
    | '/playbook'
    | '/practice'
    | '/predictions'
    | '/review'
    | '/pair/$pairId'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/backtest'
    | '/forecast'
    | '/ingestion'
    | '/learning'
    | '/notes'
    | '/playbook'
    | '/practice'
    | '/predictions'
    | '/review'
    | '/pair/$pairId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  BacktestRoute: typeof BacktestRoute
  ForecastRoute: typeof ForecastRoute
  IngestionRoute: typeof IngestionRoute
  LearningRoute: typeof LearningRoute
  NotesRoute: typeof NotesRoute
  PlaybookRoute: typeof PlaybookRoute
  PracticeRoute: typeof PracticeRoute
  PredictionsRoute: typeof PredictionsRoute
  ReviewRoute: typeof ReviewRoute
  PairPairIdRoute: typeof PairPairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingestion': {
      id: '/ingestion'
      path: '/ingestion'
      fullPath: '/ingestion'
      preLoaderRoute: typeof IngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playbook': {
      id: '/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof PlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$pairId': {
      id: '/pair/$pairId'
      path: '/pair/$pairId'
      fullPath: '/pair/$pairId'
      preLoaderRoute: typeof PairPairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  BacktestRoute: BacktestRoute,
  ForecastRoute: ForecastRoute,
  IngestionRoute: IngestionRoute,
  LearningRoute: LearningRoute,
  NotesRoute: NotesRoute,
  PlaybookRoute: PlaybookRoute,
  PracticeRoute: PracticeRoute,
  PredictionsRoute: PredictionsRoute,
  ReviewRoute: ReviewRoute,
  PairPairIdRoute: PairPairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
