/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as LearningRouteImport } from './routes/learning'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PairPairIdRouteImport } from './routes/pair.$pairId'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningRoute = LearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PairPairIdRoute = PairPairIdRouteImport.update({
  id: '/pair/$pairId',
  path: '/pair/$pairId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRoute
  '/forecast': typeof ForecastRoute
  '/learning': typeof LearningRoute
  '/notes': typeof NotesRoute
  '/review': typeof ReviewRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/forecast'
    | '/learning'
    | '/notes'
    | '/review'
    | '/pair/$pairId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/forecast'
    | '/learning'
    | '/notes'
    | '/review'
    | '/pair/$pairId'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/forecast'
    | '/learning'
    | '/notes'
    | '/review'
    | '/pair/$pairId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRoute: typeof AnalysisRoute
  ForecastRoute: typeof ForecastRoute
  LearningRoute: typeof LearningRoute
  NotesRoute: typeof NotesRoute
  ReviewRoute: typeof ReviewRoute
  PairPairIdRoute: typeof PairPairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning': {
      id: '/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof LearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$pairId': {
      id: '/pair/$pairId'
      path: '/pair/$pairId'
      fullPath: '/pair/$pairId'
      preLoaderRoute: typeof PairPairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRoute: AnalysisRoute,
  ForecastRoute: ForecastRoute,
  LearningRoute: LearningRoute,
  NotesRoute: NotesRoute,
  ReviewRoute: ReviewRoute,
  PairPairIdRoute: PairPairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
