/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PairPairIdRouteImport } from './routes/pair.$pairId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PairPairIdRoute = PairPairIdRouteImport.update({
  id: '/pair/$pairId',
  path: '/pair/$pairId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pair/$pairId': typeof PairPairIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pair/$pairId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pair/$pairId'
  id: '__root__' | '/' | '/pair/$pairId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PairPairIdRoute: typeof PairPairIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair/$pairId': {
      id: '/pair/$pairId'
      path: '/pair/$pairId'
      fullPath: '/pair/$pairId'
      preLoaderRoute: typeof PairPairIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PairPairIdRoute: PairPairIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
